receivers:
  otlp:
    protocols:
      http:

exporters:
  prometheus:
    endpoint: "0.0.0.0:8888"
  otlphttp/victoria:
    endpoint: http://victoriametrics:8428

service:
  pipelines:
    traces:
      receivers: [otlp]
      exporters: [otlphttp/victoria]
