name: Redeploy Docker Compose App on Push to Master

on:
  push:
    branches:
      - main

jobs:
  redeploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Deploy App via SSH
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          port: 22
          script: |
            echo "Checking Secrets..."
            echo "HOST: ${{ secrets.SERVER_HOST }}"
            echo "USER: ${{ secrets.SERVER_USER }}"
            echo "SSH key length: $(echo "${{ secrets.SERVER_SSH_KEY }}" | wc -c)"
            echo "Pulling latest code..."
            cd ~/TestDeploy  # Replace this with the actual path on your EC2
            git pull origin master
            echo "Stopping existing containers..."
            docker-compose down
            echo "Starting containers with GPU support..."
            docker-compose up -d --build
            echo "Deployment completed!"

